const toggleMenu = document.querySelector('.toggle')
const Section = document.querySelector('section')
const Glass = document.querySelector('.glass')

const About = document.querySelector('.about')
About.addEventListener('click', () => {
    Section.classList.toggle('toggle--active')
    Glass.classList.toggle('toggle--active')
    About.classList.toggle('toggle--active')
    Tour.classList.remove('toggle--active--tour')
    Section.classList.remove('toggle--active--tour')
    Glass.classList.remove('toggle--active--tour')
    Section.classList.remove('toggle--active--contact')
    Glass.classList.remove('toggle--active--contact')
    Contact.classList.remove('toggle--active--contact')
})

const Tour = document.querySelector('.tour')
Tour.addEventListener('click', () => {
    Section.classList.toggle('toggle--active--tour')
    Glass.classList.toggle('toggle--active--tour')
    Tour.classList.toggle('toggle--active--tour')
    About.classList.remove('toggle--active')
    Section.classList.remove('toggle--active')
    Glass.classList.remove('toggle--active')
    Section.classList.remove('toggle--active--contact')
    Glass.classList.remove('toggle--active--contact')
    Contact.classList.remove('toggle--active--contact')
})

const Contact = document.querySelector('.contact')
Contact.addEventListener('click', () => {
    Section.classList.toggle('toggle--active--contact')
    Glass.classList.toggle('toggle--active--contact')
    Contact.classList.toggle('toggle--active--contact')
    About.classList.remove('toggle--active')
    Section.classList.remove('toggle--active')
    Glass.classList.remove('toggle--active')
    About.classList.remove('toggle--active--tour')
    Section.classList.remove('toggle--active--tour')
    Glass.classList.remove('toggle--active--tour')
    Tour.classList.remove('toggle--active--tour')
})

const Home = document.querySelector('.home')
Home.addEventListener('click', () => {
    Section.classList.remove('toggle--active')
    Section.classList.remove('toggle--active--tour')
    Section.classList.remove('toggle--active--contact')
    Glass.classList.remove('toggle--active')
    Glass.classList.remove('toggle--active--tour')
    Glass.classList.remove('toggle--active--contact')
    Tour.classList.remove('toggle--active--tour')
    About.classList.remove('toggle--active')
    Contact.classList.remove('toggle--active--contact')
})